version: '3.8'

services:
  frontend:
    build:
      context: ./exchange-converter
      dockerfile: Dockerfile.app
    ports:
      - "4200:80"  # Map NGINX port 80 to localhost 4200 for Angular
    depends_on:
      - backend
    volumes:
      - node_modules_cache:/app/node_modules  # Optional cache for node_modules

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - node_modules_cache:/usr/src/app/node_modules  # Optional cache for node_modules
    command: ["./wait-for-it.sh", "db:5432", "--", "node", "dist/server.js"]

  db:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  pgdata:
  node_modules_cache:  # Shared cache volume for node_modules

